# Generated by Django 5.2.6 on 2025-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_apartment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
