# Generated by Django 5.2.6 on 2025-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_apartment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
    ]
