# Generated by Django 5.2.6 on 2025-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id_image_url',
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
