# Generated by Django 5.2.6 on 2025-11-10 22:24

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_national_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.house_image_upload_path)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('rent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='accounts.landlordprofile')),
            ],
            options={
                'verbose_name': 'Vacant House',
                'verbose_name_plural': 'Vacant Houses',
                'ordering': ['-created_at'],
            },
        ),
    ]
